apiVersion: v1
kind: Pod
metadata:
  name: core-pod
  labels:
    app: web-app-server
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}

  containers:
    - name: web-server
      image: local-optimized-web:v1
      imagePullPolicy: Never
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx/

    - name: log-monitor
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            if [ -f /app/logs/access.log ];
            then tail -n 1 /app/logs/access.log;
            fi; 
            sleep 5; 
          done
      volumeMounts:
        - name: shared-logs
          mountPath: /app/logs/

---
apiVersion: v1
kind: Service
metadata:
  name: service-kubernetes
spec:
  type: NodePort
  selector:
    app: web-app-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
